name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run tests and generate coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=./src --cov-report=xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: ./src
          args: >
            -Dsonar.projectKey=thomascode1210_sonarcloud-github
            -Dsonar.organization=thomascode1210
            -Dsonar.sources=.
            -Dsonar.python.coverageReportPaths=coverage.xml